# Generated by Django 2.2.9 on 2020-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200813_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
